version: '2'
services:
  yunohost:
    image: 'yunohost:withdependencies'
    privileged: true
    restart: always
    container_name: yunohost
    hostname: test.local
    network_mode: host
    command: ["/bin/systemd"]
    volumes:
      - media:/media

volumes:
  media:
